"""empty message

Revision ID: 1e3f13e6db4b
Revises: a180f2c77fad
Create Date: 2024-11-05 00:43:40.209452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e3f13e6db4b'
down_revision = 'a180f2c77fad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reparacion', schema=None) as batch_op:
        batch_op.alter_column('check_list_pago',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=15),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reparacion', schema=None) as batch_op:
        batch_op.alter_column('check_list_pago',
               existing_type=sa.String(length=15),
               type_=sa.BOOLEAN(),
               existing_nullable=True)

    # ### end Alembic commands ###
